name: Workflow Docker

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      #-
      #  name: Checkout
      #  uses: actions/checkout@v2
      # https://github.com/marketplace/actions/docker-login
      #-
      #  name: Set up Docker Buildx
      #  uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      # https://github.com/marketplace/actions/build-and-push-docker-images
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: abe520/ubuntu-vnc-firefox-32bit:latest